### ISSUE TITLE
[19.3] Audio Spatialization very audibly incorrect in Level 1 

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#10]
Open the project up in 2019.3.0f1

Load up the Level1 scene and with headphones on enter Play Mode.

Proceed through the level normally until you open the gate and enter the temple-y part of the level.
At this point you can very audibly hear echoes of most sound effects - especially the staff swish and Ellen's jump.

Walk around from the top of the stairs on the left side of the temple to the top of the right side whilst performing these sound effects and you will be able to pick up on how much louder than the music they are and how they suddenly don't match the audio-scape unlike earlier on in the level.

**Comment by UnityGuillaume** [comment]
Don't look like a bug, but a feature : there is a reverb zone that cover the whole of the temple that does that, disablign thatr everbe zone remove that reverb so I guess it's always been like that?
