### ISSUE TITLE
[19.3.0f6] Project opens with TerrainData obsolete warnings 

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#12]
Open the project in 2019.3.0f6.

Upon importing you will notice the following 4 errors in the console:

![image](https://user-images.githubusercontent.com/29916701/73850748-309f7300-4824-11ea-8c46-b2035f648365.png)

These are all in the BlendedTerrain.cs script in 

Assets\3DGamekit\Scripts\Game\Graphics\BlendedTerrain.cs

**Comment by UnityGuillaume** [comment]
I'm a bit scared to take such drastic measure but...look like that script is used nowhere in the project.

It require a terrain, but unless I'm mistaken there is no more Terrain anywhere in the project, we use probuilder mesh now no?

**Comment by Jacekpapapolski** [comment]
Deleted from the project and tested - everything seems fine! Going to push and upload
