### ISSUE TITLE
Audio Source warnings spam console when you enter Level 1, Level 2

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#2]
When you enter Level 1/Level 2 in Play Mode, you'll get the following warnings constantly spammed in the console for anything that has an audio source:
Effect Resonance Audio Renderer could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.
Same bug as 3DGKL: https://github.cds.internal.unity3d.com/unity/gamekit3d-lite/issues/1

**Comment by UnityGuillaume** [comment]
Should be fixed by the attached commit (it's on a 19.1-update branch)

Was caused by Resonance audio plugin beign part of the Resonance Google VR package, re-added the package so it's properly usable.

**Comment by Jacekpapapolski** [comment]
Warnings no longer showing up as of a3d41a7 - Closing!
