### ISSUE TITLE
[Win] Shaders broken - Game View entirely black with artefacts

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#4]
Same issue as 3DGKL - https://github.cds.internal.unity3d.com/unity/gamekit3d-lite/issues/2

Launching any scene from the 3DGK causes multiple shader errors in the console, leaves the game view all black with artefacts displayed on the screen.
https://gyazo.com/200cc4a1b1ee162ba64e3a3bfe2cd38e

The following errors appear in the console:

Shader error in 'Hidden/PostProcessing/DeferredFog': failed to open source file: '../StdLib.hlsl' at line 7 (on d3d11)

Compiling Vertex program with FOG_LINEAR
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_HARDWARE_TIER3 UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING

Shader error in 'Hidden/PostProcessing/MultiScaleVO': failed to open source file: '../StdLib.hlsl' at line 9 (on d3d11)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_HARDWARE_TIER3 UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING

**Comment by UnityGuillaume** [comment]
@Jacekpapapolski can't repro. Seeing the error it look like something broke on the computer where some file where missing/couldn't be accessed on your computer? The shader couldn't get compiled.

Was it clean pull? (no Library folder pre-existing)

**Comment by Jacekpapapolski** [comment]
Fixed by re-importing PostProc package - was some local error
