### ISSUE TITLE
[19.3] Failed to create Convex Mesh error in console on import / entering Play Mode

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#9]
Open the project in 2019.3.0f1

Observe the following console in the error:

`Failed to create Convex Mesh from source mesh "FloorCircular01_LOD00". Reached the maximum polygons limit (256). Consider simplifying your mesh.`

The error shows up once on entering Play mode in Level1 and 9 times in Level2

**Comment by JackTilling** [comment]
https://issuetracker.unity3d.com/issues/the-error-failed-to-create-convex-mesh-from-source-mesh-appears-when-convex-is-toggled-in-mesh-collider-settings

**Comment by Jacekpapapolski** [comment]
Fixed in be96432 - Closing!

**Comment by PeterDrake** [comment]
I'm still getting this message in 2019.3.14f1.
